# Generated by Django 4.2 on 2023-05-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва сервісу')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Назва сервісу')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='Назва сервісу')),
                ('service_image', models.ImageField(upload_to='services/', verbose_name='Основне зображення')),
                ('url', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Сервіс',
                'verbose_name_plural': 'Сервіси',
            },
        ),
    ]
