# Generated by Django 4.2 on 2023-05-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uk', models.CharField(max_length=100, verbose_name='uk Назва продукту/послуги')),
                ('name_en', models.CharField(max_length=100, verbose_name='en Назва продукту/послуги')),
                ('description_uk', models.TextField(verbose_name='Опис продукту uk (бажано 500 символів)')),
                ('description_en', models.TextField(verbose_name='Опис продукту en (бажано 500 символів)')),
                ('product_image', models.ImageField(upload_to='equipment/', verbose_name='Основне зображення')),
                ('draft', models.BooleanField(default=False, verbose_name='Чернетка')),
                ('url', models.SlugField(max_length=20)),
            ],
        ),
    ]
