# Generated by Django 4.2 on 2023-05-02 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Назва типу кузова')),
                ('name_en', models.CharField(max_length=25, null=True, verbose_name='Назва типу кузова')),
                ('name_uk', models.CharField(max_length=25, null=True, verbose_name='Назва типу кузова')),
                ('url', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип кузова',
                'verbose_name_plural': 'Типи кузовів',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2010, verbose_name='Рік випуску')),
                ('car_weight', models.FloatField(default=0, verbose_name='Масс авто')),
                ('main_image', models.ImageField(upload_to='cars/car_main_images/', verbose_name='Основне зображення')),
                ('description_uk', models.TextField(verbose_name='Опис автомобіля (мінімум 500 символів)')),
                ('description_en', models.TextField(verbose_name='Опис автомобіля (мінімум 500 символів)')),
                ('price', models.IntegerField(default=0, verbose_name='Ціна ($)')),
                ('car_speeds', models.PositiveSmallIntegerField(default=5, verbose_name='Кількість передач')),
                ('engine_volume', models.PositiveSmallIntegerField(default=0, verbose_name="Об'єм двигуна (см^3)")),
                ('power', models.PositiveSmallIntegerField(default=0, verbose_name='Потужність (к.с.)')),
                ('dimensions', models.CharField(verbose_name='Габарити (позначати як ДхШхВ)')),
                ('draft', models.BooleanField(default=False, verbose_name='Чернетка')),
                ('url', models.SlugField(max_length=100)),
                ('body_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.bodytype', verbose_name='Тип кузова')),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
            },
        ),
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Марка')),
                ('url', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категорія')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Категорія')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='Категорія')),
                ('url', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Колір')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Колір')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='Колір')),
                ('hex', models.CharField(max_length=100, verbose_name='Hex номер кольору')),
                ('url', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Колір',
                'verbose_name_plural': 'Кольори',
            },
        ),
        migrations.CreateModel(
            name='DriveUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Назва приводу')),
                ('name_en', models.CharField(max_length=25, null=True, verbose_name='Назва приводу')),
                ('name_uk', models.CharField(max_length=25, null=True, verbose_name='Назва приводу')),
                ('url', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Привід',
                'verbose_name_plural': 'Приводи',
            },
        ),
        migrations.CreateModel(
            name='EngineTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип двигуна')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Тип двигуна')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='Тип двигуна')),
                ('url', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип двигуна',
                'verbose_name_plural': 'Типи двигунів',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Коробка передач')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Коробка передач')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='Коробка передач')),
                ('url', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Коробка передач',
                'verbose_name_plural': 'Коробки передач',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель')),
                ('url', models.SlugField(max_length=100)),
                ('mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmark', verbose_name='')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Моделі',
            },
        ),
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Назва зображення')),
                ('name_en', models.CharField(max_length=25, null=True, verbose_name='Назва зображення')),
                ('name_uk', models.CharField(max_length=25, null=True, verbose_name='Назва зображення')),
                ('image', models.ImageField(upload_to='cars/car_images_lists/', verbose_name='Зображення')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Автомобіль')),
            ],
            options={
                'verbose_name': 'Зображення',
                'verbose_name_plural': 'Зображення',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ManyToManyField(to='cars.category', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ManyToManyField(to='cars.colors', verbose_name='Колір'),
        ),
        migrations.AddField(
            model_name='car',
            name='drive_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.driveunit', verbose_name='Привід'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.enginetypes', verbose_name='Тип двигуна'),
        ),
        migrations.AddField(
            model_name='car',
            name='mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmark', verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.carmodel', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.ManyToManyField(to='cars.transmission', verbose_name='Коробка передач'),
        ),
    ]
