# Generated by Django 4.2 on 2023-05-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_ua',
            field=models.IntegerField(default=0, verbose_name='Ціна (грн.)'),
        ),
    ]
