# Generated by Django 4.2 on 2023-05-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_price_ua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.ManyToManyField(blank=True, to='cars.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.ManyToManyField(blank=True, to='cars.colors', verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.ManyToManyField(blank=True, to='cars.transmission', verbose_name='Коробка передач'),
        ),
    ]
