# Generated by Django 4.2 on 2023-05-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Назва баннера')),
                ('name_en', models.CharField(max_length=25, null=True, verbose_name='Назва баннера')),
                ('name_uk', models.CharField(max_length=25, null=True, verbose_name='Назва баннера')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннери',
            },
        ),
    ]
