# Generated by Django 4.2 on 2023-05-02 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Char',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва характеристики')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Назва характеристики')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='Назва характеристики')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Charcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва категорії характеристик')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Назва категорії характеристик')),
                ('name_uk', models.CharField(max_length=50, null=True, verbose_name='Назва категорії характеристик')),
            ],
            options={
                'verbose_name': 'Категорія характеристики',
                'verbose_name_plural': 'Категорії характеристик',
            },
        ),
        migrations.CreateModel(
            name='Complect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва комплектації')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Назва комплектації')),
                ('name_uk', models.CharField(max_length=50, null=True, verbose_name='Назва комплектації')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.car', verbose_name='Автомобіль')),
                ('char_category', models.ManyToManyField(to='complect.charcategory', verbose_name='Категорія характеристик')),
                ('drive_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.driveunit', verbose_name='Привід')),
            ],
            options={
                'verbose_name': 'Комплектація',
                'verbose_name_plural': 'Комплектації',
            },
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False, verbose_name='Наявність в комплектації')),
                ('char', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='complect.char', verbose_name='Характеристика')),
                ('complectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complect.complect', verbose_name='Комплектація')),
            ],
            options={
                'verbose_name': 'Значення',
                'verbose_name_plural': 'Значення',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100, verbose_name='Ціна комплектації')),
                ('price_bf', models.CharField(max_length=100, verbose_name='Ціна комплектації + чорний дах')),
                ('complectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complect.complect', verbose_name='Комплектація')),
                ('transmission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.transmission', verbose_name='Коробки передач')),
            ],
        ),
        migrations.AddField(
            model_name='char',
            name='char_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='complect.charcategory', verbose_name='Категорія характеристик'),
        ),
    ]
