# Generated by Django 4.2 on 2023-05-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complect',
            name='char',
            field=models.ManyToManyField(null=True, to='complect.char', verbose_name='Список характеристик в комплектації'),
        ),
    ]
