# Generated by Django 4.2 on 2023-05-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complect', '0002_complect_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='char',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Назва характеристики'),
        ),
        migrations.AlterField(
            model_name='char',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Назва характеристики'),
        ),
        migrations.AlterField(
            model_name='char',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Назва характеристики'),
        ),
    ]
