# Generated by Django 4.2 on 2023-05-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complect', '0004_alter_prices_price_bf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='price_bf',
            field=models.CharField(default=0, max_length=100, null=True, verbose_name='Ціна комплектації + чорний дах (0 якщо не потрібно)'),
        ),
    ]
