# Generated by Django 4.2 on 2023-05-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complect', '0005_alter_prices_price_bf'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='price_bf_ua',
            field=models.CharField(default=0, max_length=100, null=True, verbose_name='Ціна комплектації (грн.) + чорний дах (0 якщо не потрібно)'),
        ),
        migrations.AddField(
            model_name='prices',
            name='price_ua',
            field=models.CharField(default=1, max_length=100, verbose_name='Ціна комплектації (грн.)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Ціна комплектації ($)'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='price_bf',
            field=models.CharField(default=0, max_length=100, null=True, verbose_name='Ціна комплектації ($) + чорний дах (0 якщо не потрібно)'),
        ),
    ]
